version: '3.9'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: stunting
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  fastapi:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql+aiomysql://user:pass@db/mydb"
    ports:
      - "8000:8000"
